import type { Metadata } from 'next'
import { Oswald, JetBrains_Mono, Source_Serif_4, Rubik } from 'next/font/google'
import './globals.scss'
import { Header } from '@/components/Header/Header'
import { Footer } from '@/components/Footer/Footer'

const heading = Rubik({ subsets: ['latin', 'cyrillic'], variable: '--heading' })
const jbMono = JetBrains_Mono({ subsets: ['cyrillic', 'latin'], variable: '--jbMono' })
const sourceSerif = Source_Serif_4({ subsets: ['latin', 'cyrillic'], variable: '--sourceSans' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${heading.variable} ${sourceSerif.variable} ${jbMono.variable}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
